server:
    port: 8080
spring:
    application:
        name: TEST_ITRUM
    datasource:
        url: jdbc:postgresql://localhost:5432/testdb
        username: postgres
        password: admin3006
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    liquibase:
        change-log: classpath:liquibase/changelog.yml
        enabled: true
